language: c
dist: trusty

os:
  - linux

env:
  global:
    - condition=$(cat condition)

#branches: 
  #only:
  #  - new

#if: branch = new

before_install:
  # fetch toolchian gcc4.9
  - echo "before install"

stages:
  - name: build
    if: tag IS present

jobs:
  # stage script can parallel.
  include:
    if: env(condition) = new
    - stage: build
      script:
      - make
      after_success:
        - echo "build success"
        - echo "push to server_chan?"

before_deploy:
  - echo "before_deploy"

deploy:
  skip_cleanup: true
  provider: releases
  token: $github_oauth_key
  on:
    tags: true
  file: 
    - hello

after_deploy:
  - echo "deploy success?"
  - echo "push to server_chan?"
