language: c
dist: trusty

os:
  - linux

branches: 
  only:
    - new

before_install:
  # fetch toolchian gcc4.9
  - echo "before install"

jobs:
  # stage script can parallel.
  include:
      - stage: build
        script:
        - make
        after_success:
          - echo "build success"
          - echo "push to server_chan?"

stages:
  #- build
  - name: build
    if: tag IS present
  #- name: push to github
  #  if: tag IS present

before_deploy:
  - echo "before_deploy"

deploy:
  skip_cleanup: true
  provider: releases
  token: $github_oauth_key
  on:
    tags: true
  file: 
    - hello

after_deploy:
  - echo "deploy success?"
  - echo "push to server_chan?"