language: c
dist: trusty

os:
  - linux

branches: 
  only:
    - new

before_install:
  # fetch toolchian gcc4.9
  - echo "before install"

jobs:
  # job parallel
  include:
    - if: tag IS present
      stage: build
      script: 
      - make

stages:
  - build

after_success:
  - echo "build success"

deploy:
  skip_cleanup: true
  provider: releases
  token: $github_oauth_key
  on:
    tags: true
  file: 
    - hello

after_deploy:
  - echo "deploy success?"

